### PR TITLE
Change run_cpu_tests.sh and pytorch-version-tests.yml

### LINKED ISSUE #2602: Scheduled workflow failed
Oh no, something went wrong in the scheduled workflow **PyTorch version tests with commit 9175f392a1384bb7a07b7308a3cef472e5e7f027**.
Please look into it:

https://github.com/pytorch/ignite/actions/runs/2485275378

Feel free to close this if this was just a one-off error.

### PR DESCRIPTION
**Pull request by sadra-barikbin**
Fixes #2602 

Description:

Check list:

- [ ] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

### CODE REVIEW

File: tests/run_cpu_tests.sh [hunk 1]
```diff
@@ -8,7 +8,9 @@ else
     skip_distrib_opt=(-m "")
 fi
 
-CUDA_VISIBLE_DEVICES="" pytest --tx 4*popen//python=python --cov ignite --cov-report term-missing --cov-report xml -vvv tests "${skip_distrib_opt[@]}"
+MATCH_TESTS_EXPRESSION=${1:-"true"}
```
Comment (vfdev-5) [inline tests/run_cpu_tests.sh:11]: Why `true` by default ?

Comment (vfdev-5) [reply tests/run_cpu_tests.sh]: Please check that from your side :)

**Review by vfdev-5 — APPROVED** [review]
Thanks @sadra-barikbin

**Comment by vfdev-5** [comment]
I triggered manually pytorch test version workflow: https://github.com/pytorch/ignite/actions/runs/2497811873
Let's see if this helps with time handler. I still expect it to fail due to https://github.com/pytorch/ignite/issues/2598
